apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hfqi8a4ds-python
  janus-idp.io/tekton: hfqi8a4ds-python
  backstage.io/kubernetes-id: hfqi8a4ds-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hfqi8a4ds-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
