apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hfqi8a4ds-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hfqi8a4ds-python 
  name: hfqi8a4ds-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hfqi8a4ds-python 
